### ISSUE TITLE
Determine lifecycle for relevant data

### ISSUE THREAD

**Issue by scwatts** [umccr/nextflow-stack#3]
No cleanup/removal of data is currently done. Consider lifecycle for at least:

* Nextflow work directory
* Staged data
* Previous runs i.e. WGS CUPPA after running WGTS CUPPA

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [oncoanalyser release: Decide output paths for AWS prod](https://trello.com/c/kiRSvk1M/1455-oncoanalyser-release-decide-output-paths-for-aws-prod)
