### ISSUE TITLE
Use --tag on submit_job for cost allocation purposes

### ISSUE THREAD

**Issue by brainstorm** [umccr/nextflow-stack#85]
Add a `RunId` tag parameter (and corresponding value) to [this and/or other submit_job calls](https://github.com/umccr/nextflow-stack/blob/b3f2f360ac3b2fd2dcc7119871333e419c64e2c4/application/pipeline-stacks/oncoanalyser/lambda_functions/batch_job_submission/lambda_code.py#L61). Also experiment with `propagate-tags`: https://docs.aws.amazon.com/cli/latest/reference/batch/submit-job.html

/cc @scwatts @reisingerf @andrewpatto

**Comment by scwatts** [comment]
Seems like a really good fit, and using the portal ID for `RunId` would make sense to me
